[package]
name = "logarithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checked_decimal_macro = "0.1.4"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "ln_benchmark"
harness = false